[custom]

enable_rule_generator=true
overwrite_original_rules=true
;update_ruleset_on_request=true

## Top RULE-SET ##

# > zerotier
ruleset=zerotier,[]SRC-IP-CIDR,192.168.200.249/32


ruleset=🌍Global,[]DOMAIN-SUFFIX,github.io
ruleset=🌍Global,[]DOMAIN-SUFFIX,githubusercontent.com
ruleset=🌍Global,[]DOMAIN-SUFFIX,qbittorrent.org

# 📕Comic
ruleset=📕Comic,[]DOMAIN-SUFFIX,7-zip.org
ruleset=📕Comic,[]DOMAIN-KEYWORD,18comic
ruleset=📕Comic,[]DOMAIN-KEYWORD,jmcomic

ruleset=📕Comic,[]DOMAIN-SUFFIX,mhgui.com
ruleset=📕Comic,[]DOMAIN-SUFFIX,manhuagui.com
ruleset=📕Comic,[]DOMAIN-SUFFIX,hamreus.com
ruleset=📕Comic,[]DOMAIN-SUFFIX,hamreus.com
ruleset=📕Comic,[]DOMAIN-SUFFIX,cocomanga.com
ruleset=📕Comic,[]DOMAIN-SUFFIX,noip.com

# exhentai
ruleset=📕Comic,[]DOMAIN-KEYWORD,e-hentai
ruleset=📕Comic,[]DOMAIN-KEYWORD,exhentai
ruleset=📕Comic,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EHGallery/EHGallery.list

# > Google
ruleset=📢Google,[]DOMAIN-SUFFIX,google.com
ruleset=📢Google,[]DOMAIN-SUFFIX,googleapis.com
ruleset=📢Google,[]IP-CIDR,142.250.4.90/32,no-resolve
ruleset=📢Google,[]IP-CIDR,216.239.35.0/27,no-resolve
ruleset=📢Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list


# YouTube
ruleset=📢Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list

## Auto RULE-SET ##
# Local Area Network
ruleset=DIRECT,[]IP-CIDR,0.0.0.0/8
ruleset=DIRECT,[]IP-CIDR,10.0.0.0/8
ruleset=DIRECT,[]IP-CIDR,100.64.0.0/10
ruleset=DIRECT,[]IP-CIDR,127.0.0.0/8
ruleset=DIRECT,[]IP-CIDR,169.254.0.0/16
ruleset=DIRECT,[]IP-CIDR,172.16.0.0/12
ruleset=DIRECT,[]IP-CIDR,192.0.0.0/24
ruleset=DIRECT,[]IP-CIDR,192.0.2.0/24
ruleset=DIRECT,[]IP-CIDR,192.88.99.0/24
ruleset=DIRECT,[]IP-CIDR,192.168.0.0/16
ruleset=DIRECT,[]IP-CIDR,198.18.0.0/15
ruleset=DIRECT,[]IP-CIDR,198.51.100.0/24
ruleset=DIRECT,[]IP-CIDR,203.0.113.0/24
ruleset=DIRECT,[]IP-CIDR,224.0.0.0/4
ruleset=DIRECT,[]IP-CIDR,240.0.0.0/4
ruleset=DIRECT,[]IP-CIDR,233.252.0.0/24
ruleset=DIRECT,[]IP-CIDR,255.255.255.255/32

ruleset=DIRECT,[]DOMAIN-SUFFIX,dd.zz
ruleset=DIRECT,[]DOMAIN-SUFFIX,zh.zz
ruleset=DIRECT,[]DOMAIN-SUFFIX,bj.zz

# > Guard
;Use AdGuard Home

# > Game
ruleset=🎮Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
ruleset=🎮Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Xbox/Xbox.list
ruleset=🎮Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Nintendo/Nintendo.list
ruleset=🎮Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/PlayStation/PlayStation.list
ruleset=🎮Game,https://raw.githubusercontent.com/exernest/Config/main/Clash/SC2.list

# > Social
ruleset=🐦Social,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list
ruleset=🐦Social,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook.list

# > Telegram
ruleset=📱TelegramSG,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TelegramSG/TelegramSG.list
ruleset=📱TelegramUS,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TelegramUS/TelegramUS.list
ruleset=📱TelegramNL,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TelegramNL/TelegramNL.list
ruleset=📱Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list

# > Region
ruleset=🌍Global,[]DOMAIN-SUFFIX,nyaa.si
ruleset=🌍Global,[]DOMAIN-SUFFIX,sukebei.nyaa.si
ruleset=🌍Global,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Pixiv/Pixiv.list
ruleset=🌍Global,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/MEGA/MEGA.list

# JP Region
ruleset=日本,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/Region/JP.list
ruleset=日本,[]DOMAIN-SUFFIX,mora.jp
ruleset=日本,[]DOMAIN-SUFFIX,dlsite.com

# > PayPal
ruleset=💰PayPal,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.list

# > Spotify
ruleset=🎵Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
# Media
ruleset=🎵Spotify,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/Streaming.list

# > AppleProxy
#ruleset=🌍Global,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleProxy/AppleProxy.list

ruleset=🚩Final,[]FINAL

## proxy_groups ##
custom_proxy_group=🌍Global`select`[]Auto`[]香港`[]台湾`[]韩国`[]日本`[]新加坡`[]美国`[]其他
custom_proxy_group=📢Google`select`[]Auto`[]🌍Global`[]香港`[]台湾`[]韩国`[]日本`[]新加坡`[]美国`[]其他
custom_proxy_group=📕Comic`select`[]Auto`[]🌍Global`[]香港`[]台湾`[]韩国`[]日本`[]新加坡`[]美国`[]其他
custom_proxy_group=🎮Game`select`[]Auto`[]香港`[]台湾`[]韩国`[]日本`[]新加坡`[]美国`[]其他`[]DIRECT
custom_proxy_group=🐦Social`select`[]Auto`[]🌍Global
custom_proxy_group=🎵Spotify`select`[]Auto`[]🌍Global`[]香港`[]台湾`[]韩国`[]日本`[]新加坡`[]美国`[]其他
custom_proxy_group=📱Telegram`select`[]Auto`[]🌍Global
custom_proxy_group=💰PayPal`select`[]Auto`[]🌍Global`[]香港`[]台湾`[]韩国`[]日本`[]新加坡`[]美国`[]其他
custom_proxy_group=🚩Final`select`[]DIRECT`[]🌍Global
custom_proxy_group=📱TelegramSG`select`[]📱Telegram`[]新加坡`http://captive.apple.com`600,,100
custom_proxy_group=📱TelegramUS`select`[]📱Telegram`[]美国`http://captive.apple.com`600,,100
custom_proxy_group=📱TelegramNL`select`[]📱Telegram`[]欧洲`http://captive.apple.com`600,,100

custom_proxy_group=Auto`url-test`(?=.*(香港|澳门|日本|美国|台湾|狮城|韩国))`http://captive.apple.com`600,,100
custom_proxy_group=香港`url-test`(?=.*(香港|澳门))`http://cp.cloudflare.com/generate_204`600,,100
custom_proxy_group=日本`url-test`(?=.*(日本))`http://cp.cloudflare.com/generate_204`600,,100
custom_proxy_group=美国`url-test`(?=.*(美国))`http://cp.cloudflare.com/generate_204`600,,100
custom_proxy_group=台湾`url-test`(?=.*(台湾))`http://cp.cloudflare.com/generate_204`600,,100
custom_proxy_group=韩国`url-test`(?=.*(韩国))`http://cp.cloudflare.com/generate_204`600,,100
custom_proxy_group=新加坡`url-test`(?=.*(狮城))`http://cp.cloudflare.com/generate_204`600,,100
custom_proxy_group=欧洲`url-test`(?=.*(德国|法国|英国))`http://cp.cloudflare.com/generate_204`600,,100
custom_proxy_group=zerotier`select`(?=.*(香港|澳门|日本|美国|台湾|狮城|韩国))
custom_proxy_group=其他`select`(?=.*)^((?!(香港|澳门|日本|美国|台湾|狮城|韩国|德国|法国|英国|UnblockMusic)).)*$
